### ISSUE TITLE
Door unlocking but not locking -- something's wrong with async

### ISSUE THREAD

**Issue by datapolitical** [ZacheryThomas/srpy#5]
Here's what the quickstart example looks like when I run it:

❯ python lock_test.py
lock_test.py:13: RuntimeWarning: coroutine 'sleep' was never awaited
  asyncio.sleep(10)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

What happens is that it logs in fine and then unlocks the door but doesn't lock it again.

**Comment by ZacheryThomas** [comment]
Hi!

Thanks for reaching out. I believe i fixed the issue with my latest [commit](https://github.com/ZacheryThomas/smartrent.py/commit/30065c6b7fd437d29a6dd464b4cf520e93d0dfe0). Turns out I was missing the `await` keyword before `asyncio.sleep(10)`. If you check out the docs now it should be up to date and work as intended.

https://smartrentpy.readthedocs.io/en/latest/examples.html#changing-the-state-of-a-doorlock
